# Generated by Django 5.1.3 on 2024-11-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_evento_codigo_postal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='codigo_postal',
            field=models.CharField(max_length=5),
        ),
    ]
