# Generated by Django 5.1.3 on 2024-11-18 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='espacio',
            old_name='horario_apertura',
            new_name='hora_apertura',
        ),
        migrations.RenameField(
            model_name='espacio',
            old_name='horario_cierre',
            new_name='hora_cierre',
        ),
    ]
