# Generated by Django 5.1.3 on 2024-11-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='espacio',
            old_name='horario_apertura',
            new_name='hora_apertura',
        ),
        migrations.RenameField(
            model_name='espacio',
            old_name='horario_cierre',
            new_name='hora_cierre',
        ),
        migrations.AddField(
            model_name='espacio',
            name='dependencias',
            field=models.ManyToManyField(blank=True, to='espacios.espacio'),
        ),
    ]
