# Generated by Django 5.1.3 on 2024-11-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0002_rename_horario_apertura_espacio_hora_apertura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacio',
            name='codigo_postal',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
