# Generated by Django 4.2.16 on 2024-11-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0002_rename_horario_apertura_espacio_hora_apertura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacio',
            name='dependencias',
            field=models.ManyToManyField(blank=True, to='espacios.espacio'),
        ),
    ]
