# Generated by Django 5.1.3 on 2024-11-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0003_espacio_codigo_postal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacio',
            name='codigo_postal',
            field=models.CharField(max_length=5),
        ),
    ]
