# Generated by Django 5.1.3 on 2024-11-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0004_alter_espacio_codigo_postal'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacio',
            name='autorizacion',
            field=models.BooleanField(default=False),
        ),
    ]
