# Generated by Django 5.1.3 on 2024-12-03 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0005_espacio_autorizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenEspacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='static/images/espacios/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='espacios.espacio')),
            ],
        ),
    ]
