# Generated by Django 5.1.3 on 2024-12-03 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0006_imagenespacio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenespacio',
            name='descripcion',
        ),
    ]
