# Generated by Django 5.1.3 on 2024-11-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_codigo_postal_usuario_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contador',
            field=models.IntegerField(default=0),
        ),
    ]
