# Generated by Django 5.1.3 on 2024-11-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_apellidos_usuario_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPueblo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pueblo', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=5, unique=True)),
                ('escudo', models.ImageField(blank=True, null=True, upload_to='escudos/')),
            ],
        ),
    ]
