# Generated by Django 5.1.3 on 2024-11-28 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_configuracionpueblo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracionPueblo',
        ),
    ]
