# Generated by Django 5.1.3 on 2024-11-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='codigo_postal',
            field=models.CharField(default='00000', max_length=5),
        ),
    ]
