# Generated by Django 5.1.3 on 2024-11-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='codigo_postal',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
