# Generated by Django 5.1.3 on 2024-11-25 23:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_reserva_codigo_postal'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='grupo_reserva',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
