# Generated by Django 5.1.3 on 2024-11-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_alter_reserva_codigo_postal'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='autorizada',
            field=models.BooleanField(default=False),
        ),
    ]
