# Generated by Django 5.1.3 on 2024-11-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion_total', models.PositiveIntegerField(default=0)),
                ('numero_votos', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
